#!/bin/bash

# Import configuration from file
if [ $# -lt 1 ]; then
  echo "Error: At least one argument is required."
  exit 1
fi
CONFIGURATION_FILE=$1
source $CONFIGURATION_FILE

# Export each variable
for var in PYTHON_SCRIPT INPUT_SCRIPT CONFIGURATION_FILE CONDA_ENVIRONMENT SERPENT_DATA SERPENT_ACELIB SERPENT_DECLIB SERPENT_NFYLIB SERPENT_EXE
do
    export $var
done

########################################### NO CHANGE NECESSARY BEYOND THAT POINT ###########################################
if [ -n "$SUFFIX_JOB" ]; then
  SUFFIX_JOB="_${SUFFIX_JOB}"
fi
export JOB_NAME=$(basename $INPUT_SCRIPT | cut -d. -f1)${SUFFIX_JOB}

# Remove Serpent data if not existing
for var in SERPENT_DATA SERPENT_ACELIB SERPENT_DECLIB SERPENT_NFYLIB; do
    if [ -z "${!var}" ]; then
        unset $var
    fi
done

# Print job information
echo "Running HxF with 1 task with the following parameters:"
echo "------------------------------------------------------"
echo "Job name: ${JOB_NAME}"
echo "Script: ${PYTHON_SCRIPT}"
echo "Input script: ${INPUT_SCRIPT}"
echo "Environment loaded from: ${CONFIGURATION_FILE} (conda environment: ${CONDA_ENVIRONMENT})"
echo "Serpent path: ${SERPENT_EXE}"
echo "Nuclear data path: ${SERPENT_DATA} (${SERPENT_ACELIB}, ${SERPENT_DECLIB}, ${SERPENT_NFYLIB})"
echo "------------------------------------------------------"

# Load the environment
source ${CONFIGURATION_FILE} ${CONDA_ENVIRONMENT}

# Run the Python script
python ${PYTHON_SCRIPT} ${INPUT_SCRIPT}